/* =========================================================
   SAAK Catalog Manager — edits scripts/products.js in the
   GitHub repository via the Contents API, from any browser
   (built for phones). Each add/remove is one commit; GitHub
   Pages redeploys the store automatically.

   Requires a fine-grained personal access token scoped to
   ONLY this repository with "Contents: Read and write".
   ========================================================= */

const ADMIN = {
  owner: 'thoriumrobot',
  repo: 'online-clothing-store',
  branch: 'master',
  path: 'scripts/products.js',
  categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
  images: [
    'images/tee.svg', 'images/hoodie.svg', 'images/trousers.svg',
    'images/dress.svg', 'images/overshirt.svg', 'images/cap.svg',
    'images/tote.svg', 'images/scarf.svg', 'images/product1.jpg',
  ],
};

let token = '';
let fileSha = '';
let products = [];

const $ = (sel) => document.querySelector(sel);
const peso = (n) => '\u20b1' + n.toLocaleString('en-PH', { minimumFractionDigits: 2 });

// ---------- status ----------
function status(msg, kind) {
  const el = $('#status');
  el.hidden = !msg;
  el.textContent = msg || '';
  el.className = 'admin-status ' + (kind || 'ok');
}

// ---------- UTF-8-safe base64 ----------
function b64encode(str) {
  const bytes = new TextEncoder().encode(str);
  let bin = '';
  bytes.forEach((b) => { bin += String.fromCharCode(b); });
  return btoa(bin);
}
function b64decode(b64) {
  const bin = atob(b64.replace(/\s/g, ''));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
}

// ---------- products.js parse / serialize ----------
// Must round-trip with the format written by manage-products.js.
function parseProducts(source) {
  const match = /const PRODUCTS = \[\n([\s\S]*?)\n\];/.exec(source);
  if (!match) throw new Error('Unrecognized products.js format');
  return JSON.parse('[' + match[1] + ']');
}

function serializeProducts(list) {
  const rows = list.map((p) => {
    const parts = [
      `"id": ${JSON.stringify(p.id)}`,
      `"name": ${JSON.stringify(p.name)}`,
      `"price": ${p.price.toFixed(2)}`,
      `"category": ${JSON.stringify(p.category)}`,
      `"img": ${JSON.stringify(p.img)}`,
    ];
    if (p.badge) parts.push(`"badge": ${JSON.stringify(p.badge)}`);
    return `  { ${parts.join(', ')} }`;
  });
  return `/* =========================================================
   SAAK — product catalog (data only)
   Edit by hand, or use the CLI from the project root:
     node manage-products.js list
     node manage-products.js add "Wool Beanie" 22.00 accessories images/cap.svg "New"
     node manage-products.js remove p7
   This file is regenerated by the CLI — keep the format.
   ========================================================= */
(function () {
const PRODUCTS = [
${rows.join(',\n')}
];

/* Works both in the browser and in Node (for the CLI and tests) */
if (typeof module !== 'undefined') module.exports = PRODUCTS;
if (typeof window !== 'undefined') window.SAAK_PRODUCTS = PRODUCTS;
})();
`;
}

// ---------- GitHub Contents API ----------
const apiUrl = () =>
  `https://api.github.com/repos/${ADMIN.owner}/${ADMIN.repo}/contents/${ADMIN.path}`;

function ghHeaders() {
  return {
    'Authorization': 'Bearer ' + token,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  };
}

async function loadCatalog() {
  const res = await fetch(`${apiUrl()}?ref=${ADMIN.branch}&t=${Date.now()}`, { headers: ghHeaders() });
  if (res.status === 401 || res.status === 403) throw new Error('Token rejected — check it has Contents: Read and write on this repository.');
  if (res.status === 404) throw new Error('Catalog file not found — check the repository name and branch.');
  if (!res.ok) throw new Error('GitHub returned an error (' + res.status + '). Try again.');
  const data = await res.json();
  fileSha = data.sha;
  products = parseProducts(b64decode(data.content));
}

async function commitCatalog(message) {
  const res = await fetch(apiUrl(), {
    method: 'PUT',
    headers: ghHeaders(),
    body: JSON.stringify({
      message: '[catalog] ' + message,
      content: b64encode(serializeProducts(products)),
      sha: fileSha,
      branch: ADMIN.branch,
    }),
  });
  if (res.status === 409) {
    await loadCatalog();
    renderList();
    throw new Error('The catalog changed elsewhere and was reloaded — please redo your edit.');
  }
  if (res.status === 401 || res.status === 403) throw new Error('Token rejected — reconnect with a valid token.');
  if (!res.ok) throw new Error('Save failed (' + res.status + '). Your change was not committed — try again.');
  const data = await res.json();
  fileSha = data.content.sha;
}

// ---------- UI ----------
function nextId() {
  const max = products.reduce((m, p) => {
    const n = /^p(\d+)$/.exec(p.id);
    return n ? Math.max(m, parseInt(n[1], 10)) : m;
  }, 0);
  return 'p' + (max + 1);
}

function renderList() {
  const box = $('#itemList');
  $('#itemCount').textContent = products.length;
  box.innerHTML = '';
  products.forEach((p) => {
    const row = document.createElement('div');
    row.className = 'admin-item';
    row.innerHTML = `
      <img src="${p.img}" alt="">
      <div class="admin-item-info">
        <strong></strong>
        <span>${p.id} · ${p.category} · <span class="mono">${peso(p.price)}</span>${p.badge ? ' · ' + p.badge : ''}</span>
      </div>
      <button class="admin-remove">Remove</button>`;
    row.querySelector('strong').textContent = p.name;
    row.querySelector('.admin-remove').addEventListener('click', () => removeItem(p.id));
    box.appendChild(row);
  });
}

function setBusy(busy) {
  document.querySelectorAll('#manageView button').forEach((b) => { b.disabled = busy; });
}

async function addItem() {
  const name = $('#newName').value.trim();
  const price = parseFloat($('#newPrice').value);
  const category = $('#newCategory').value;
  const img = $('#newImage').value;
  const badge = $('#newBadge').value.trim();

  if (!name) return status('Enter an item name.', 'err');
  if (!isFinite(price) || price <= 0) return status('Enter a valid price above zero.', 'err');
  if (products.some((p) => p.name.toLowerCase() === name.toLowerCase())) {
    return status(`"${name}" already exists — remove it first or pick another name.`, 'err');
  }

  const item = { id: nextId(), name, price, category, img };
  if (badge) item.badge = badge;

  setBusy(true);
  status('Saving to GitHub…');
  try {
    products.push(item);
    await commitCatalog(`add ${item.name} (${item.id})`);
    renderList();
    $('#newName').value = ''; $('#newPrice').value = ''; $('#newBadge').value = '';
    status(`Added ${item.name} — live site updates in ~1–2 minutes.`);
  } catch (e) {
    products = products.filter((p) => p.id !== item.id);
    renderList();
    status(e.message, 'err');
  }
  setBusy(false);
}

async function removeItem(id) {
  const idx = products.findIndex((p) => p.id === id);
  if (idx === -1) return;
  const [gone] = products.splice(idx, 1);

  setBusy(true);
  status('Saving to GitHub…');
  try {
    await commitCatalog(`remove ${gone.name} (${gone.id})`);
    renderList();
    status(`Removed ${gone.name} — live site updates in ~1–2 minutes.`);
  } catch (e) {
    products.splice(idx, 0, gone);
    renderList();
    status(e.message, 'err');
  }
  setBusy(false);
}

async function connect() {
  token = $('#tokenInput').value.trim();
  if (!token) return status('Paste your access token first.', 'err');
  status('Connecting…');
  try {
    await loadCatalog();
    if ($('#rememberToken').checked) localStorage.setItem('saak_admin_token', token);
    sessionStorage.setItem('saak_admin_token', token);
    $('#authView').hidden = true;
    $('#manageView').hidden = false;
    $('#logoutBtn').hidden = false;
    renderList();
    status(`Connected — ${products.length} items in the catalog.`);
  } catch (e) {
    status(e.message, 'err');
  }
}

function logout() {
  token = '';
  localStorage.removeItem('saak_admin_token');
  sessionStorage.removeItem('saak_admin_token');
  $('#manageView').hidden = true;
  $('#logoutBtn').hidden = true;
  $('#authView').hidden = false;
  $('#tokenInput').value = '';
  status('');
}

function init() {
  // image choices
  const sel = $('#newImage');
  ADMIN.images.forEach((img) => {
    const o = document.createElement('option');
    o.value = img;
    o.textContent = img.replace('images/', '');
    sel.appendChild(o);
  });

  $('#connectBtn').addEventListener('click', connect);
  $('#addBtn').addEventListener('click', addItem);
  $('#logoutBtn').addEventListener('click', logout);

  const saved = sessionStorage.getItem('saak_admin_token') || localStorage.getItem('saak_admin_token');
  if (saved) {
    $('#tokenInput').value = saved;
    connect();
  }
}

if (typeof document !== 'undefined') {
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
}

if (typeof module !== 'undefined') {
  module.exports = { parseProducts, serializeProducts };
}
